from screeninfo import get_monitors

TIME_TICK = 120

DSCREEN_WIDTH, DSCREEN_HEIGHT = 1920, 1080
DEFAULT_SCREEN = (DSCREEN_WIDTH, DSCREEN_HEIGHT)

# SCREEN_WIDTH, SCREEN_HEIGHT = get_monitors()[0].width, get_monitors()[0].height
# SCREEN_WIDTH, SCREEN_HEIGHT = 960, 540
SCREEN_WIDTH, SCREEN_HEIGHT = 1920, 1080
SCREEN = (SCREEN_WIDTH, SCREEN_HEIGHT)

SCALE_X, SCALE_Y = SCREEN[0] / DEFAULT_SCREEN[0], SCREEN[1] / DEFAULT_SCREEN[1]
SCALE = int((SCALE_X + SCALE_Y) / 2)

GAME_STATES = ["Instruction", "MainMenu", "Game", "DeathScreen", "Results", "Close", "InGamePause"]
